enum EVENTS {
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  SHUFFLE_WHITE_CARDS = 'SHUFFLE_WHITE_CARDS',
  SHUFFLE_BLACK_CARDS = 'SHUFFLE_BLACK_CARDS',
  DRAW_WHITE_CARD = 'DRAW_WHITE_CARD',
  DRAW_BLACK_CARD = 'DRAW_BLACK_CARD',
  PLAY_CARD = 'PLAY_CARD',
  REVEAL_CARD = 'REVEAL_CARD',
  UPDATE_ROOM = 'UPDATE_ROOM',
}

export default EVENTS;
