enum EVENTS {
  JOIN_ROOM = 'JOIN_ROOM',
  LEAVE_ROOM = 'LEAVE_ROOM',
  DRAW_WHITE_CARD = 'DRAW_WHITE_CARD',
  DRAW_BLACK_CARD = 'DRAW_BLACK_CARD',
  PLAY_CARD = 'PLAY_CARD',
  REVEAL_CARD = 'REVEAL_CARD',
  UPDATE_ROOM = 'UPDATE_ROOM',
  CHOOSE_WINNING_CARD = 'CHOOSE_WINNING_CARD',
  END_OF_ROUND = 'END_OF_ROUND',
  RESTART_GAME = 'RESTART_GAME',
  GAME_RESTARTED = 'GAME_RESTARTED',
}

export default EVENTS;
